// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: competition.proto

package song_contest_rater_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heat int32

const (
	Heat_HEAT_UNSPECIFIED     Heat = 0
	Heat_HEAT_SEMI_FINAL      Heat = 1
	Heat_HEAT_FINAL           Heat = 2
	Heat_HEAT_1               Heat = 3
	Heat_HEAT_2               Heat = 4
	Heat_HEAT_3               Heat = 5
	Heat_HEAT_4               Heat = 6
	Heat_HEAT_5               Heat = 7
	Heat_HEAT_FINAL_QUALIFIER Heat = 8
)

// Enum value maps for Heat.
var (
	Heat_name = map[int32]string{
		0: "HEAT_UNSPECIFIED",
		1: "HEAT_SEMI_FINAL",
		2: "HEAT_FINAL",
		3: "HEAT_1",
		4: "HEAT_2",
		5: "HEAT_3",
		6: "HEAT_4",
		7: "HEAT_5",
		8: "HEAT_FINAL_QUALIFIER",
	}
	Heat_value = map[string]int32{
		"HEAT_UNSPECIFIED":     0,
		"HEAT_SEMI_FINAL":      1,
		"HEAT_FINAL":           2,
		"HEAT_1":               3,
		"HEAT_2":               4,
		"HEAT_3":               5,
		"HEAT_4":               6,
		"HEAT_5":               7,
		"HEAT_FINAL_QUALIFIER": 8,
	}
)

func (x Heat) Enum() *Heat {
	p := new(Heat)
	*p = x
	return p
}

func (x Heat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Heat) Descriptor() protoreflect.EnumDescriptor {
	return file_competition_proto_enumTypes[0].Descriptor()
}

func (Heat) Type() protoreflect.EnumType {
	return &file_competition_proto_enumTypes[0]
}

func (x Heat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Heat.Descriptor instead.
func (Heat) EnumDescriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{0}
}

type GetCompetitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCompetitionRequest) Reset() {
	*x = GetCompetitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionRequest) ProtoMessage() {}

func (x *GetCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{0}
}

func (x *GetCompetitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateCompetitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Heat      Heat                   `protobuf:"varint,1,opt,name=heat,proto3,enum=songcontestrater.Heat" json:"heat,omitempty"`
	City      string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country   string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ImageUrl  string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *CreateCompetitionRequest) Reset() {
	*x = CreateCompetitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionRequest) ProtoMessage() {}

func (x *CreateCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompetitionRequest) GetHeat() Heat {
	if x != nil {
		return x.Heat
	}
	return Heat_HEAT_UNSPECIFIED
}

func (x *CreateCompetitionRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateCompetitionRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateCompetitionRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateCompetitionRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateCompetitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Heat      Heat                   `protobuf:"varint,2,opt,name=heat,proto3,enum=songcontestrater.Heat" json:"heat,omitempty"`
	City      string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country   string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ImageUrl  string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *UpdateCompetitionRequest) Reset() {
	*x = UpdateCompetitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionRequest) ProtoMessage() {}

func (x *UpdateCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCompetitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCompetitionRequest) GetHeat() Heat {
	if x != nil {
		return x.Heat
	}
	return Heat_HEAT_UNSPECIFIED
}

func (x *UpdateCompetitionRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateCompetitionRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateCompetitionRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateCompetitionRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type DeleteCompetitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCompetitionRequest) Reset() {
	*x = DeleteCompetitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompetitionRequest) ProtoMessage() {}

func (x *DeleteCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompetitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCompetitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CompetitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Heat      Heat                   `protobuf:"varint,2,opt,name=heat,proto3,enum=songcontestrater.Heat" json:"heat,omitempty"`
	City      string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country   string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ImageUrl  string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Acts      []*ActResponse         `protobuf:"bytes,7,rep,name=acts,proto3" json:"acts,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *CompetitionResponse) Reset() {
	*x = CompetitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompetitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionResponse) ProtoMessage() {}

func (x *CompetitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionResponse.ProtoReflect.Descriptor instead.
func (*CompetitionResponse) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{4}
}

func (x *CompetitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompetitionResponse) GetHeat() Heat {
	if x != nil {
		return x.Heat
	}
	return Heat_HEAT_UNSPECIFIED
}

func (x *CompetitionResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CompetitionResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CompetitionResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CompetitionResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CompetitionResponse) GetActs() []*ActResponse {
	if x != nil {
		return x.Acts
	}
	return nil
}

func (x *CompetitionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CompetitionResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListCompetitionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Competitions []*CompetitionResponse `protobuf:"bytes,1,rep,name=competitions,proto3" json:"competitions,omitempty"`
}

func (x *ListCompetitionsResponse) Reset() {
	*x = ListCompetitionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCompetitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompetitionsResponse) ProtoMessage() {}

func (x *ListCompetitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompetitionsResponse.ProtoReflect.Descriptor instead.
func (*ListCompetitionsResponse) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{5}
}

func (x *ListCompetitionsResponse) GetCompetitions() []*CompetitionResponse {
	if x != nil {
		return x.Competitions
	}
	return nil
}

var File_competition_proto protoreflect.FileDescriptor

var file_competition_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x6f, 0x6e, 0x67, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x72, 0x1a, 0x09, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xcc, 0x01, 0x0a, 0x18, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x6f, 0x6e, 0x67, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x74, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0xdc, 0x01, 0x0a, 0x18, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x6f, 0x6e, 0x67, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x74, 0x52, 0x04, 0x68, 0x65,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x80, 0x03, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x6f, 0x6e,
	0x67, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65,
	0x61, 0x74, 0x52, 0x04, 0x68, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x31,
	0x0a, 0x04, 0x61, 0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73,
	0x6f, 0x6e, 0x67, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x72, 0x2e,
	0x41, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x61, 0x63, 0x74,
	0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x65, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x6f, 0x6e, 0x67,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0x97,
	0x01, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x45, 0x41, 0x54, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0f, 0x48, 0x45, 0x41, 0x54, 0x5f, 0x53, 0x45, 0x4d, 0x49, 0x5f, 0x46, 0x49, 0x4e, 0x41, 0x4c,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x48, 0x45, 0x41, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x41, 0x4c,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x54, 0x5f, 0x31, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x48, 0x45, 0x41, 0x54, 0x5f, 0x32, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45,
	0x41, 0x54, 0x5f, 0x33, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x54, 0x5f, 0x34,
	0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x54, 0x5f, 0x35, 0x10, 0x07, 0x12, 0x18,
	0x0a, 0x14, 0x48, 0x45, 0x41, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x41, 0x4c, 0x5f, 0x51, 0x55, 0x41,
	0x4c, 0x49, 0x46, 0x49, 0x45, 0x52, 0x10, 0x08, 0x42, 0x1c, 0x5a, 0x1a, 0x2e, 0x3b, 0x73, 0x6f,
	0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_competition_proto_rawDescOnce sync.Once
	file_competition_proto_rawDescData = file_competition_proto_rawDesc
)

func file_competition_proto_rawDescGZIP() []byte {
	file_competition_proto_rawDescOnce.Do(func() {
		file_competition_proto_rawDescData = protoimpl.X.CompressGZIP(file_competition_proto_rawDescData)
	})
	return file_competition_proto_rawDescData
}

var file_competition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_competition_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_competition_proto_goTypes = []any{
	(Heat)(0),                        // 0: songcontestrater.Heat
	(*GetCompetitionRequest)(nil),    // 1: songcontestrater.GetCompetitionRequest
	(*CreateCompetitionRequest)(nil), // 2: songcontestrater.CreateCompetitionRequest
	(*UpdateCompetitionRequest)(nil), // 3: songcontestrater.UpdateCompetitionRequest
	(*DeleteCompetitionRequest)(nil), // 4: songcontestrater.DeleteCompetitionRequest
	(*CompetitionResponse)(nil),      // 5: songcontestrater.CompetitionResponse
	(*ListCompetitionsResponse)(nil), // 6: songcontestrater.ListCompetitionsResponse
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
	(*ActResponse)(nil),              // 8: songcontestrater.ActResponse
}
var file_competition_proto_depIdxs = []int32{
	0,  // 0: songcontestrater.CreateCompetitionRequest.heat:type_name -> songcontestrater.Heat
	7,  // 1: songcontestrater.CreateCompetitionRequest.start_time:type_name -> google.protobuf.Timestamp
	0,  // 2: songcontestrater.UpdateCompetitionRequest.heat:type_name -> songcontestrater.Heat
	7,  // 3: songcontestrater.UpdateCompetitionRequest.start_time:type_name -> google.protobuf.Timestamp
	0,  // 4: songcontestrater.CompetitionResponse.heat:type_name -> songcontestrater.Heat
	7,  // 5: songcontestrater.CompetitionResponse.start_time:type_name -> google.protobuf.Timestamp
	8,  // 6: songcontestrater.CompetitionResponse.acts:type_name -> songcontestrater.ActResponse
	7,  // 7: songcontestrater.CompetitionResponse.created_at:type_name -> google.protobuf.Timestamp
	7,  // 8: songcontestrater.CompetitionResponse.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 9: songcontestrater.ListCompetitionsResponse.competitions:type_name -> songcontestrater.CompetitionResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_competition_proto_init() }
func file_competition_proto_init() {
	if File_competition_proto != nil {
		return
	}
	file_act_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_competition_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetCompetitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competition_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCompetitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competition_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCompetitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competition_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteCompetitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competition_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CompetitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competition_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListCompetitionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_competition_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_competition_proto_goTypes,
		DependencyIndexes: file_competition_proto_depIdxs,
		EnumInfos:         file_competition_proto_enumTypes,
		MessageInfos:      file_competition_proto_msgTypes,
	}.Build()
	File_competition_proto = out.File
	file_competition_proto_rawDesc = nil
	file_competition_proto_goTypes = nil
	file_competition_proto_depIdxs = nil
}
